config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "callbacks" }

  #devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  #devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants

  get 'home/choosed' => 'home#choosed'
  root 'home#index'
  get 'home/randomselect/:id' => 'home#randomselect', as: 'randomselect'

  #get "*path" => redirect("/")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
 include CanCan::Ability
 
  def initialize(user)
    if user
      if user.kind == 'admin'
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :restaurant
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :restaurant

  has_attached_file :asset,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method: 
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	translates :description
  accepts_nested_attributes_for :translations, allow_destroy: true
	validates :name, presence: true
  has_many :galleries, :dependent => :destroy
  has_many :comments, :dependent => :destroy

	# attr_reader :asset_remote_url
  # has_attached_file :asset,
  #   :styles => {
  #     :thumb => "100x100#",
  #     :small  => "150x150>",
  #     :medium => "200x200" }
  #validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  #attr_accessor :delete_asset
  #before_validation { self.asset.clear if self.delete_asset == '1' }


  # def asset_remote_url=(url_value)
  #   self.asset = URI.parse(url_value)
  #   # Assuming url_value is http://example.com/photos/face.png
  #   # asset_file_name == "face.png"
  #   # asset_content_type == "image/png"
  #   @asset_remote_url = url_value
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action  :set_session_location_ative
  


   	private

	def store_current_location
	  store_location_for(:member, request.url)
	end


	def set_locale
		I18n.locale = session[:current_locale_session] || I18n.default_locale
	end

	def set_session_location_ative
		if !params[:locale].blank?
		  #puts "AAAAAAAA #{params[:locale]}  AAAAAA"
		  session[:current_locale_session] = params[:locale]
		  set_locale
		end
	end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
    redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
require 'nokogiri'
require 'open-uri'
class HomeController < ApplicationController
  def index
   	@total = Restaurant.all.count
   	#@random_restaurant = Restaurant.where(chosen: true).sample
	@random_restaurant = Restaurant.all.sample
  end
  def choosed
   	@total = Restaurant.all.count
   	@lista = Restaurant.where(chosen: true)
  end

  # GET /randomselect/1
  # GET /randomselect/1.json
  def randomselect
    @restaurant = Restaurant.find(params[:id])
  end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
    redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
   	root_path
  end

  def after_inactive_sign_up_path_for(resource)
   root_path
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :asset, :chosen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def check_admin(user)
		user.kind == 'admin'
	end

	def sentence
    ["À la carte", 
    "As easy as pie",
    "As keen as mustard",
    "Cut the mustard",
    "Eat drink and be merry",
    "Finger lickin' good",
    "It is meat and drink to me",
    "Let them eat cake ",
    "My cup of tea",
    "Done to a turn",
    "You are what you eat",
    "Whet your appetite"].sample
	end

	def h_rest_name(restaurant)
		title, slogan = restaurant.name.split(/-/)
		{"title" => title, "slogan" => slogan}
	end
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

app/views/home/choosed.html.erb
<p id="notice"><%= notice %></p>

<!-- All Restaurants Section -->
<section class="content-section">
  <div class="all-section">
    <div class="container">
      <div class="col-lg-12 text-center">
        <div class="section-heading">
          <h2>You've tried</h2>
        </div>
      </div>
      <span class="toggler active" data-toggle="4"><span class="fa fa-th"></span></span>
      <span class="toggler" data-toggle="2"><span class="fa fa-bars"></span></span>
      <div class="restaurants__wrapper">
        <ul class="restaurant--grid" data-column="4">
          <% @lista.each do |restaurant| %>
           <li class="restaurant--column">
                <%= link_to restaurant_path(restaurant), :class => "restaurant__info" do %>
                  <div class="restaurant__info__image"><%= image_tag restaurant.avatar.url(:medium) %></div>
                  <div class="restaurant__info__title"><%= h_rest_name(restaurant)["title"] %></div>
                  <div class="restaurant__info__slogan"><%=h_rest_name(restaurant)["slogan"] %></div>
                <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<!-- Intro Header -->
<header class="intro">
	<div class="intro-body">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<%#= debug %>
					<% if user_signed_in? && check_admin(current_user) %>
                	<%= link_to randomselect_path(@random_restaurant), :class => "secret__link" do %>
        					<h1 class="brand-heading"> What will I eat today? </h1>
                            <p class="intro-text"><%= sentence %></p>

                            <span class="btn btn-primary btn-lg">
                                <i class="fa fa-cutlery"></i> Raffle now!
                            </span>
                        <% end %>
					<% else %>
						<h1 class="brand-heading"> What will I eat today? </h1>
						<p class="intro-text">Login to find out!</p>
					<% end %>
					<%#= debug @random_restaurant %>
				</div>
			</div>
		</div>
	</div>
</header>

<script type="text/javascript">
    //  $('.secret__link').each(function(){
    //      $(this).attr('onclick','window.location.href="'+$(this).attr('href')+'"');
    //      $(this).attr('href','');
    //  });
</script>

app/views/home/randomselect.html.erb
<div class="loading"></div>

<section class="show-section">
	<div class="content">
		<div id="logo" class="content__image-wrap content__image--right">
			<%= image_tag @restaurant.avatar.url, :class => "content__image" if @restaurant.avatar? %>
		</div>
		<div class="clearfix"></div>
		<h2 class="content__title content__title--right">
			<%= link_to @restaurant.link, :target => "_blank", :class => "content__title__link" do %>
			<div id="title" class="content__title__inner"><%= h_rest_name(@restaurant)["title"] %></div>
			<div id="slogan" class="content__title__inner content__title__inner--offset-1"><%= h_rest_name(@restaurant)["slogan"] %></div>
			<% end %>
		</h2>

		<div class="content__actions text-right">
			<%= link_to root_path, :class => "btn btn-default btn-lg" do %>
				<i class="fa fa-frown-o"></i> I'd rather starve
			<% end %>

			<%= link_to @restaurant.link, :target => "_blank", :class => "btn btn-inverse btn-lg" do %>
				<i class="fa fa-cutlery"></i> Order
			<% end %>
		</div>

	</div>
</section>

<script>
	(function() {
			// Fake loading.
			setTimeout(init, 1000);

			function init() {

				document.querySelector('.loading').remove();

				var revTitle = new RevealFx(document.querySelector('#title'), {
					revealSettings : {
						bgcolor: '#333',
						onCover: function(contentEl, revealerEl) {
							contentEl.style.opacity = 1;
						}
					}
				});
				revTitle.reveal();

				var revSlogan = new RevealFx(document.querySelector('#slogan'), {
					revealSettings : {
						bgcolor: '#333',
						delay: 250,
						onCover: function(contentEl, revealerEl) {
							contentEl.style.opacity = 1;
						}
					}
				});
				revSlogan.reveal();

				var revLogo = new RevealFx(document.querySelector('#logo'), {
						revealSettings : {
							bgcolor: '#FFFFFF',
							delay: 300,
							direction: 'rl',
							onCover: function(contentEl, revealerEl) {
								contentEl.style.opacity = 1;
							}
						}
					});
				revLogo.reveal();

				var buttons = new RevealFx(document.querySelector('.content__actions'), {
					revealSettings : {
						bgcolor: '#FFFFFF',
						delay: 300,
						direction: 'rl',
						onCover: function(contentEl, revealerEl) {
							contentEl.style.opacity = 1;
						}
					}
				});
				buttons.reveal();


			}
		})();
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>The Secret Order</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

	<!-- Navigation -->
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
	  	<div class="container">
	  		<div class="navbar-header">
	  			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
	  				Menu <i class="fa fa-bars"></i>
	  			</button>
	  			<%= link_to root_path, :class => "navbar-brand page-scroll" do %>
	                <i class="fa fa-cutlery"></i> <span class="light">The</span> Secret <span class="light">Order</span>
	            <% end %>
	  		</div>

	  		<div class="collapse navbar-collapse navbar-right navbar-main-collapse">
	  			<ul class="nav navbar-nav">
	  				<li class="hidden">
	  					<a href="#page-top"></a>
	  				</li>
	  				<li>
	  					<%= link_to home_choosed_path, :class => "page-scroll" do %>
	  					Chosen
	  					<% end %>
	  				</li>
	  				<li>
	  					<%= link_to restaurants_path, :class => "page-scroll" do %>
	  					Restaurants
	  					<% end %>
	  				</li>

	  				<% if user_signed_in? %>
            <% if current_user.image.present? %>
                <%= image_tag(current_user.image, size: "40") %>
            <% end %>
	  				<li class="dropdown">
	  					<a class="dropdown-toggle page-scroll" data-toggle="dropdown" href="#">
	  					<%= current_user.name %>
	  						<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
	  					</a>
	  					<ul class="dropdown-menu dropdown-user">
	  						<li>
	  							<i class="fa fa-sign-out fa-fw"></i>
	  							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	  							<%= link_to('Edit Account', edit_user_registration_path) %>
	  						</li>
	  					</ul>
					</li>
					<% else %>
					<li>
						<%= link_to 'Login', new_user_session_path,  { :class => "page-scroll" } %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>


      <% if notice %>
      <div class="alert alert-success">
        <strong><%= notice %></strong>
      </div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger">
        <strong><%= alert %> </strong>
      </div>
      <% end %>
      <%= yield %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    </body>

</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant,:multipart => true) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :asset %>
     <%= image_tag @restaurant.avatar.url if @restaurant.avatar? %>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :chosen %>
    <%= f.check_box :chosen %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_show.html.erb
	<div class="cd-slider-wrapper">
		<ul class="cd-slider">
			<li class="selected"><%= image_tag @restaurant.avatar.url, :class => "content__image" if @restaurant.avatar? %></li>
		</ul>

		<!-- <ul class="cd-slider-navigation">
			<li><a class="cd-next" href="#0">Prev</a></li>
			<li><a class="cd-prev" href="#0">Next</a></li>
		</ul>  -->
	</div>

	<div class="cd-item-info">
		<h2><%= h_rest_name(@restaurant)["title"] %> <br>
		<small><%= h_rest_name(@restaurant)["slogan"] %></small></h2>
		<p><%= t(@restaurant.description) %></p>

		<ul class="cd-item-action">
			<!-- <li><button class="add-to-cart">Add to cart</button></li>					 -->
			<!-- <li><a href="#0">Learn more</a></li>	 -->
		</ul>
	</div>
	<span class="cd-close">Close</span>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<!-- All Restaurants Section -->
<section class="content-section">
  <div class="all-section">
    <div class="container">
      <div class="col-lg-12 text-center">
        <div class="section-heading">
          <h2>Limited Options, Unlimited Fun</h2>
          <p class="text-muted">Check out what you can get one of these days!</p>
        </div>
      </div>
      <span class="toggler active" data-toggle="4"><span class="fa fa-th"></span></span>
      <span class="toggler" data-toggle="2"><span class="fa fa-bars"></span></span>
      <div class="restaurants__wrapper">
        <ul class="restaurant--grid" data-column="4">
          <% @restaurants.each do |restaurant| %>
           <li class="restaurant--column">
                <%= link_to restaurant_path(restaurant), remote: true, :class => "restaurant__info" do %>
                  <div class="restaurant__info__image"><%= image_tag restaurant.avatar.medium.url %></div>
                  <div class="restaurant__info__title"><%= h_rest_name(restaurant)["title"] %></div>
                  <div class="restaurant__info__slogan"><%=h_rest_name(restaurant)["slogan"] %></div>
                <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>
  <div class="cd-quick-view"></div>
<script type="text/javascript">

window.onload = function() {
    var togglers = document.getElementsByClassName('toggler');
    for(var i = 0; i < togglers.length; i++) {
         togglers[i].addEventListener('click', function() {
          if(this.classList.contains('active')) return;
          var $this = this,
              $other = document.querySelector('.toggler.active'),
              thisMode = $this.getAttribute('data-toggle');
              document.querySelector('.restaurant--grid').setAttribute('data-column', thisMode);

          $other.classList.remove('active');
          $this.classList.add('active');
        });
    }
}


</script>

app/views/restaurants/show.html.erb
<section class="content-section">
  <div class="show-section">
    <div class="container">
      <div class="col-lg-12 text-center">
      <%= image_tag @restaurant.avatar.url, :class => "content__image" if @restaurant.avatar? %>
        <h2><%= h_rest_name(@restaurant)["title"] %> <br>
		<small><%= h_rest_name(@restaurant)["slogan"] %></small></h2>
		<p><%= @restaurant.description %></p>

      </div>
    </div>
  </div>
</section>

app/views/restaurants/show.js.erb
  $(".cd-quick-view").html('<%= j render "restaurants/show" %>');